CREATE TABLE transactions(
	id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	user INT NOT NULL,
	type INT NOT NULL,
	amount DEC(14, 2) NOT NULL DEFAULT(0.00),
	date DATE NOT NULL DEFAULT(CURRENT_DATE),
	concept INT NOT NULL
);